language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

before_script:
  - cp -rf site-admin/assets/site/css/index.css site-admin/dist/css/

script:
  - cd site-admin && npm run deploy


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: site-admin/build
  on:
    branch: master
