language: node_js

node_js:
  - "stable"
  
cache:
  directories:
  - node_modules

before_script:
  - cp -rf assets/site/css/index.css dist/css/

script:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
